import styled from '@emotion/styled'
import { Typography, Container } from '@mui/material'
import Head from 'next/head'
import Image from 'next/image'
import AuthGoogle from '../components/AuthGoogle'
import styles from '../styles/Home.module.css'

const TitleLetter = styled.span`
  padding-right: 5px;
  color: #EFFFFF;
  font-size: 100px;
  font-family: calibri;
  font-weight: 700;
  opacity: ${props => (props.opacity / 100)}
`

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Shadow - Path to 100k</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='main'>
        <div className='title'>
          <TitleLetter opacity={100} color={"green"}>S</TitleLetter>
          <TitleLetter opacity={90} color={"black"}>h</TitleLetter>
          <TitleLetter opacity={80} color={"red"}>a</TitleLetter>
          <TitleLetter opacity={70} color={"gray"}>d</TitleLetter>
          <TitleLetter opacity={60} color={"blue"}>o</TitleLetter>
          <TitleLetter opacity={50} color={"indigo"}>w</TitleLetter>
        </div>
        <AuthGoogle />
      </div>
    </div>
  )
}
